{"uid":"49c3ad3bfc23e8c2","name":"A Service Provider tries to activates a debtor without having the correct credentials","fullName":"A Debtor Service Providers activates a debtor: A Service Provider tries to activates a debtor without having the correct credentials","historyId":"758493b92a8e7facc3a5995f0f6eedd0","time":{"start":1759476894990,"stop":1759476895639,"duration":649},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/activation_steps.py\", line 32, in then_sp_fails_activation_wrong_credentials\n    assert context.latest_activation_response.status_code == 401\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/activation_steps.py\", line 32, in then_sp_fails_activation_wrong_credentials\n    assert context.latest_activation_response.status_code == 401\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Given the debtor A has fiscal code random","time":{"start":1759476894991,"stop":1759476894991,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"And the debtor Service Provider is unauthenticated","time":{"start":1759476894991,"stop":1759476894991,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When the debtor Service Provider tries to activate the debtor A","time":{"start":1759476894991,"stop":1759476895637,"duration":646},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then the activation fails because the Service Provider has wrong credentials","time":{"start":1759476895637,"stop":1759476895638,"duration":1},"status":"failed","statusMessage":"AssertionError\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/activation_steps.py\", line 32, in then_sp_fails_activation_wrong_credentials\n    assert context.latest_activation_response.status_code == 401\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":4,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"activation"},{"name":"tag","value":"authentication"},{"name":"tag","value":"unhappy_path"},{"name":"feature","value":"A Debtor Service Providers activates a debtor"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":4,"unknown":0,"total":5},"items":[{"uid":"a7f573ce230013d9","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/551//#testresult/a7f573ce230013d9","status":"passed","time":{"start":1759390887613,"stop":1759390888024,"duration":411}},{"uid":"4e1135cb1921ac16","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/550//#testresult/4e1135cb1921ac16","status":"passed","time":{"start":1759316292510,"stop":1759316293028,"duration":518}},{"uid":"e32fb3e9cec6e5db","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/549//#testresult/e32fb3e9cec6e5db","status":"passed","time":{"start":1759303852503,"stop":1759303853118,"duration":615}},{"uid":"d459cdb5fac74beb","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/548//#testresult/d459cdb5fac74beb","status":"passed","time":{"start":1759217435893,"stop":1759217436357,"duration":464}}]},"tags":["activation","unhappy_path","authentication"]},"source":"49c3ad3bfc23e8c2.json","parameterValues":[]}