{"uid":"a26a790dd1e2fac2","name":"A debtor Service Provider tries to activates a debtor 2 times, failing the second attempt","fullName":"A Debtor Service Providers activates a debtor: A debtor Service Provider tries to activates a debtor 2 times, failing the second attempt","historyId":"38626e702fa9de630d34234bd0de45db","time":{"start":1759476894327,"stop":1759476894990,"duration":663},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api-mcshared.uat.cstar.pagopa.it/auth/token\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/auth_steps.py\", line 17, in given_ec_on_page\n    access_token = get_valid_access_token(client_id=client_id,\n                                          client_secret=client_secret,\n                                          access_token_function=get_access_token)\n  File \"/home/runner/work/rtp-platform-qa/rtp-platform-qa/api/auth.py\", line 8, in get_valid_access_token\n    token_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api-mcshared.uat.cstar.pagopa.it/auth/token\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/auth_steps.py\", line 17, in given_ec_on_page\n    access_token = get_valid_access_token(client_id=client_id,\n                                          client_secret=client_secret,\n                                          access_token_function=get_access_token)\n  File \"/home/runner/work/rtp-platform-qa/rtp-platform-qa/api/auth.py\", line 8, in get_valid_access_token\n    token_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[{"name":"Given the debtor Service Provider is authenticated","time":{"start":1759476894328,"stop":1759476894989,"duration":661},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api-mcshared.uat.cstar.pagopa.it/auth/token\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/auth_steps.py\", line 17, in given_ec_on_page\n    access_token = get_valid_access_token(client_id=client_id,\n                                          client_secret=client_secret,\n                                          access_token_function=get_access_token)\n  File \"/home/runner/work/rtp-platform-qa/rtp-platform-qa/api/auth.py\", line 8, in get_valid_access_token\n    token_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"And the debtor A has fiscal code random","time":{"start":1759476894990,"stop":1759476894990,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"And the debtor Service Provider activated the debtor A","time":{"start":1759476894990,"stop":1759476894990,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When the debtor Service Provider tries to activate the debtor A","time":{"start":1759476894990,"stop":1759476894990,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then the activation fails because debtor A is already activated","time":{"start":1759476894990,"stop":1759476894990,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"activation"},{"name":"tag","value":"authentication"},{"name":"tag","value":"unhappy_path"},{"name":"feature","value":"A Debtor Service Providers activates a debtor"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":4,"unknown":0,"total":5},"items":[{"uid":"35028ee3d382603b","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/551//#testresult/35028ee3d382603b","status":"passed","time":{"start":1759390885683,"stop":1759390887613,"duration":1930}},{"uid":"24e597ec1ad2100e","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/550//#testresult/24e597ec1ad2100e","status":"passed","time":{"start":1759316290215,"stop":1759316292509,"duration":2294}},{"uid":"5e4130bd4cedc525","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/549//#testresult/5e4130bd4cedc525","status":"passed","time":{"start":1759303849772,"stop":1759303852503,"duration":2731}},{"uid":"57cdfb9ed3f80d5a","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/548//#testresult/57cdfb9ed3f80d5a","status":"passed","time":{"start":1759217434029,"stop":1759217435893,"duration":1864}}]},"tags":["activation","unhappy_path","authentication"]},"source":"a26a790dd1e2fac2.json","parameterValues":[]}