{"uid":"a3d0508fb9833306","name":"Attempt to cancel a non-existing RTP","fullName":"A Creditor Service Provider can cancel a Request to Pay: Attempt to cancel a non-existing RTP","historyId":"7b6cb717fba01804677e187c90f6a66f","time":{"start":1759476896685,"stop":1759476897888,"duration":1203},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api-mcshared.uat.cstar.pagopa.it/auth/token\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/auth_steps.py\", line 17, in given_ec_on_page\n    access_token = get_valid_access_token(client_id=client_id,\n                                          client_secret=client_secret,\n                                          access_token_function=get_access_token)\n  File \"/home/runner/work/rtp-platform-qa/rtp-platform-qa/api/auth.py\", line 8, in get_valid_access_token\n    token_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api-mcshared.uat.cstar.pagopa.it/auth/token\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/auth_steps.py\", line 17, in given_ec_on_page\n    access_token = get_valid_access_token(client_id=client_id,\n                                          client_secret=client_secret,\n                                          access_token_function=get_access_token)\n  File \"/home/runner/work/rtp-platform-qa/rtp-platform-qa/api/auth.py\", line 8, in get_valid_access_token\n    token_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[{"name":"Given the debtor A has fiscal code random","time":{"start":1759476896685,"stop":1759476896685,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"And the debtor Service Provider is authenticated","time":{"start":1759476896685,"stop":1759476897887,"duration":1202},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api-mcshared.uat.cstar.pagopa.it/auth/token\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"bdd-tests/steps/auth_steps.py\", line 17, in given_ec_on_page\n    access_token = get_valid_access_token(client_id=client_id,\n                                          client_secret=client_secret,\n                                          access_token_function=get_access_token)\n  File \"/home/runner/work/rtp-platform-qa/rtp-platform-qa/api/auth.py\", line 8, in get_valid_access_token\n    token_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"And the debtor Service Provider activated the debtor A","time":{"start":1759476897888,"stop":1759476897888,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"And the creditor Service Provider is authenticated","time":{"start":1759476897888,"stop":1759476897888,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Given the creditor Service Provider sent an RTP to the debtor A","time":{"start":1759476897888,"stop":1759476897888,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"When the creditor Service Provider send a cancellation request for a non-existing RTP","time":{"start":1759476897888,"stop":1759476897888,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Then the RTP is not found","time":{"start":1759476897888,"stop":1759476897888,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":7,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"authentication"},{"name":"tag","value":"cancel"},{"name":"tag","value":"send"},{"name":"tag","value":"unhappy_path"},{"name":"feature","value":"A Creditor Service Provider can cancel a Request to Pay"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":4,"unknown":0,"total":5},"items":[{"uid":"9689c16f0681bed1","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/551//#testresult/9689c16f0681bed1","status":"passed","time":{"start":1759390894928,"stop":1759390897908,"duration":2980}},{"uid":"3d3b365b5d2a9f91","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/550//#testresult/3d3b365b5d2a9f91","status":"passed","time":{"start":1759316300501,"stop":1759316303808,"duration":3307}},{"uid":"6f26301473ca8eff","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/549//#testresult/6f26301473ca8eff","status":"passed","time":{"start":1759303862561,"stop":1759303866398,"duration":3837}},{"uid":"4d39e5c91cd63a14","reportUrl":"https://pagopa.github.io/rtp-platform-qa/bdd/548//#testresult/4d39e5c91cd63a14","status":"passed","time":{"start":1759217441937,"stop":1759217444399,"duration":2462}}]},"tags":["cancel","send","unhappy_path","authentication"]},"source":"a3d0508fb9833306.json","parameterValues":[]}