{"uid":"bee27a9b554d7a93","name":"An RTP is sent through POSTE API","fullName":"tests.test_debtor_service_provider_availability#test_send_rtp_to_poste","historyId":"9ee43ed2ff7f9ef504e1b4a4edc013a4","time":{"start":1749485086997,"stop":1749485086998,"duration":1},"status":"broken","statusMessage":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","statusTrace":"@allure.feature('RTP Send')\n    @allure.story('Service provider sends an RTP to POSTE directly')\n    @allure.title('An RTP is sent through POSTE API')\n    @pytest.mark.send\n    @pytest.mark.happy_path\n    @pytest.mark.poste\n    def test_send_rtp_to_poste():\n        rtp_data = generate_rtp_data()\n        cbi_payload = generate_cbi_rtp_data(rtp_data)\n    \n>       response = send_srtp_to_poste(cbi_payload)\n\nfunctional-tests/tests/test_debtor_service_provider_availability.py:120: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi/debtor_service_provider.py:21: in send_srtp_to_poste\n    return requests.post(\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/adapters.py:639: in send\n    self.cert_verify(conn, request.url, verify, cert)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <requests.adapters.HTTPAdapter object at 0x7f245003c0d0>\nconn = <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f2450989fd0>\nurl = 'https://rtp.coll.poste.it:446/iso20022/api/v1/sepa-request-to-pay-requests'\nverify = True\ncert = ('/home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem', '/home/runner/work/rtp-platform-qa/rtp-platform-qa/config/key.pem')\n\n    def cert_verify(self, conn, url, verify, cert):\n        \"\"\"Verify a SSL certificate. This method should not be called from user\n        code, and is only exposed for use when subclassing the\n        :class:`HTTPAdapter <requests.adapters.HTTPAdapter>`.\n    \n        :param conn: The urllib3 connection object associated with the cert.\n        :param url: The requested URL.\n        :param verify: Either a boolean, in which case it controls whether we verify\n            the server's TLS certificate, or a string, in which case it must be a path\n            to a CA bundle to use\n        :param cert: The SSL certificate to verify.\n        \"\"\"\n        if url.lower().startswith(\"https\") and verify:\n            conn.cert_reqs = \"CERT_REQUIRED\"\n    \n            # Only load the CA certificates if 'verify' is a string indicating the CA bundle to use.\n            # Otherwise, if verify is a boolean, we don't load anything since\n            # the connection will be using a context with the default certificates already loaded,\n            # and this avoids a call to the slow load_verify_locations()\n            if verify is not True:\n                # `verify` must be a str with a path then\n                cert_loc = verify\n    \n                if not os.path.exists(cert_loc):\n                    raise OSError(\n                        f\"Could not find a suitable TLS CA certificate bundle, \"\n                        f\"invalid path: {cert_loc}\"\n                    )\n    \n                if not os.path.isdir(cert_loc):\n                    conn.ca_certs = cert_loc\n                else:\n                    conn.ca_cert_dir = cert_loc\n        else:\n            conn.cert_reqs = \"CERT_NONE\"\n            conn.ca_certs = None\n            conn.ca_cert_dir = None\n    \n        if cert:\n            if not isinstance(cert, basestring):\n                conn.cert_file = cert[0]\n                conn.key_file = cert[1]\n            else:\n                conn.cert_file = cert\n                conn.key_file = None\n            if conn.cert_file and not os.path.exists(conn.cert_file):\n>               raise OSError(\n                    f\"Could not find the TLS certificate file, \"\n                    f\"invalid path: {conn.cert_file}\"\n                )\nE               OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem\n\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/adapters.py:350: OSError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1749485077345,"stop":1749485077407,"duration":62},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"RTP Send"},{"name":"story","value":"Service provider sends an RTP to POSTE directly"},{"name":"tag","value":"poste"},{"name":"tag","value":"happy_path"},{"name":"tag","value":"send"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_debtor_service_provider_availability"},{"name":"host","value":"pkrvmf6wy0o8zjz"},{"name":"thread","value":"2496-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_debtor_service_provider_availability"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":21,"skipped":0,"passed":0,"unknown":0,"total":21},"items":[{"uid":"c3ba973b883a7745","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/371//#testresult/c3ba973b883a7745","status":"broken","statusDetails":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","time":{"start":1749484928648,"stop":1749484928649,"duration":1}},{"uid":"827af6bc60b12c97","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/370//#testresult/827af6bc60b12c97","status":"broken","statusDetails":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","time":{"start":1749484606178,"stop":1749484606179,"duration":1}},{"uid":"bc9d8b47996ac2bb","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/369//#testresult/bc9d8b47996ac2bb","status":"broken","statusDetails":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","time":{"start":1749484261317,"stop":1749484261318,"duration":1}},{"uid":"9d2bd1959ccc801","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/368//#testresult/9d2bd1959ccc801","status":"broken","statusDetails":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","time":{"start":1749483917997,"stop":1749483917998,"duration":1}},{"uid":"bc1c908ec28892bf","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/365//#testresult/bc1c908ec28892bf","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa3f4335bd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749482110505,"stop":1749482243723,"duration":133218}},{"uid":"1ef618c62521d6d2","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/367//#testresult/1ef618c62521d6d2","status":"broken","statusDetails":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","time":{"start":1749482226860,"stop":1749482226861,"duration":1}},{"uid":"3b1d1e8708347a7f","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/363//#testresult/3b1d1e8708347a7f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f23978ed810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749452894016,"stop":1749453029327,"duration":135311}},{"uid":"4dcbcd30d934b284","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/362//#testresult/4dcbcd30d934b284","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fea9f8b5bd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749366444766,"stop":1749366580272,"duration":135506}},{"uid":"1160497a1c1e2dbb","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/361//#testresult/1160497a1c1e2dbb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6bd3be5bd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749280023544,"stop":1749280156288,"duration":132744}},{"uid":"e49bf7069b9f5da","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/360//#testresult/e49bf7069b9f5da","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f93f53d1810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749193631427,"stop":1749193766467,"duration":135040}},{"uid":"3782fea2bb375598","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/359//#testresult/3782fea2bb375598","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f15cf8ed810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749107264091,"stop":1749107397478,"duration":133387}},{"uid":"9b25360b035f8d59","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/358//#testresult/9b25360b035f8d59","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3b92435bd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749020842057,"stop":1749020976331,"duration":134274}},{"uid":"1ac1cebee0a60b1b","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/357//#testresult/1ac1cebee0a60b1b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fba55bedbd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748956577073,"stop":1748956711019,"duration":133946}},{"uid":"bd40d380fcaa0286","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/356//#testresult/bd40d380fcaa0286","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc5609b5810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748953141973,"stop":1748953276978,"duration":135005}},{"uid":"5270d04c91cbe826","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/355//#testresult/5270d04c91cbe826","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f34d05e5810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748934485677,"stop":1748934618907,"duration":133230}},{"uid":"2bb759c59dcf8595","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/354//#testresult/2bb759c59dcf8595","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5a311a9810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748848083041,"stop":1748848217782,"duration":134741}},{"uid":"534afbbedc1f052","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/353//#testresult/534afbbedc1f052","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe097d35bd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748761644520,"stop":1748761779538,"duration":135018}},{"uid":"42dadb0cdab8ea40","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/352//#testresult/42dadb0cdab8ea40","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8dfbaed810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748675229649,"stop":1748675363431,"duration":133782}},{"uid":"8232f4a714d43fae","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/351//#testresult/8232f4a714d43fae","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f256f6e5bd0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748588849359,"stop":1748588985253,"duration":135894}},{"uid":"a26ddc71d85f56b3","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/350//#testresult/a26ddc71d85f56b3","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc809cf1810>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1748534042365,"stop":1748534177167,"duration":134802}}]},"tags":["poste","send","happy_path"]},"source":"bee27a9b554d7a93.json","parameterValues":[]}