{"uid":"389be36f8544bbfe","name":"An RTP is sent through POSTE API","fullName":"tests.test_debtor_service_provider_availability#test_send_rtp_to_poste","historyId":"9ee43ed2ff7f9ef504e1b4a4edc013a4","time":{"start":1751094452513,"stop":1751094453454,"duration":941},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1751094369754,"stop":1751094369810,"duration":56},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"RTP Send"},{"name":"story","value":"Service provider sends an RTP to POSTE directly"},{"name":"tag","value":"poste"},{"name":"tag","value":"happy_path"},{"name":"tag","value":"send"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_debtor_service_provider_availability"},{"name":"host","value":"pkrvmbietmlfzoi"},{"name":"thread","value":"2479-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_debtor_service_provider_availability"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":2,"broken":43,"skipped":0,"passed":1,"unknown":0,"total":46},"items":[{"uid":"cd96b84a7a47383a","reportUrl":"https://pagopa.github.io/rtp-platform-qa/415//#testresult/cd96b84a7a47383a","status":"failed","statusDetails":"AssertionError: assert 400 == 201\n +  where 400 = <Response [400]>.status_code","time":{"start":1751008093938,"stop":1751008095046,"duration":1108}},{"uid":"4a87487f6f4cd98f","reportUrl":"https://pagopa.github.io/rtp-platform-qa/414//#testresult/4a87487f6f4cd98f","status":"failed","statusDetails":"AssertionError: assert 400 == 201\n +  where 400 = <Response [400]>.status_code","time":{"start":1750947026403,"stop":1750947027108,"duration":705}},{"uid":"75f1f3efacf46000","reportUrl":"https://pagopa.github.io/rtp-platform-qa/413//#testresult/75f1f3efacf46000","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='rtp.svil.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))","time":{"start":1750924199462,"stop":1750924199848,"duration":386}},{"uid":"37084c1ce0b84469","reportUrl":"https://pagopa.github.io/rtp-platform-qa/412//#testresult/37084c1ce0b84469","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='rtp.svil.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))","time":{"start":1750921680589,"stop":1750921681034,"duration":445}},{"uid":"f1cebb621de7ef9a","reportUrl":"https://pagopa.github.io/rtp-platform-qa/411//#testresult/f1cebb621de7ef9a","status":"broken","statusDetails":"requests.exceptions.SSLError: HTTPSConnectionPool(host='rtp.svil.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))","time":{"start":1750856382363,"stop":1750856382752,"duration":389}},{"uid":"9942c26c6cb20777","reportUrl":"https://pagopa.github.io/rtp-platform-qa/408//#testresult/9942c26c6cb20777","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0557b9ae90>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750835302395,"stop":1750835437140,"duration":134745}},{"uid":"50e1fa3bc6ad7af8","reportUrl":"https://pagopa.github.io/rtp-platform-qa/406//#testresult/50e1fa3bc6ad7af8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0c6865ae90>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750779068183,"stop":1750779201593,"duration":133410}},{"uid":"603513bfb03a2c9a","reportUrl":"https://pagopa.github.io/rtp-platform-qa/404//#testresult/603513bfb03a2c9a","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7895132e90>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750756725988,"stop":1750756860224,"duration":134236}},{"uid":"db3805ed02c01030","reportUrl":"https://pagopa.github.io/rtp-platform-qa/403//#testresult/db3805ed02c01030","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd1c0c560d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750748875725,"stop":1750749009662,"duration":133937}},{"uid":"e3775f28115cff1a","reportUrl":"https://pagopa.github.io/rtp-platform-qa/402//#testresult/e3775f28115cff1a","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7e56c2e0d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750684871241,"stop":1750685007600,"duration":136359}},{"uid":"5dbd3051027913fe","reportUrl":"https://pagopa.github.io/rtp-platform-qa/401//#testresult/5dbd3051027913fe","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f340528f250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750662510703,"stop":1750662646306,"duration":135603}},{"uid":"1afcbb4294de9d7c","reportUrl":"https://pagopa.github.io/rtp-platform-qa/400//#testresult/1afcbb4294de9d7c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f920765a0d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750576084541,"stop":1750576220836,"duration":136295}},{"uid":"123488b25fcbdec8","reportUrl":"https://pagopa.github.io/rtp-platform-qa/399//#testresult/123488b25fcbdec8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f99b804f250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750489651935,"stop":1750489787142,"duration":135207}},{"uid":"59c221db98d7cd86","reportUrl":"https://pagopa.github.io/rtp-platform-qa/398//#testresult/59c221db98d7cd86","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49405ef250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750403245452,"stop":1750403381968,"duration":136516}},{"uid":"900fabad7f9c371f","reportUrl":"https://pagopa.github.io/rtp-platform-qa/397//#testresult/900fabad7f9c371f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4b15363250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750335017992,"stop":1750335154023,"duration":136031}},{"uid":"8d895768597e9a96","reportUrl":"https://pagopa.github.io/rtp-platform-qa/396//#testresult/8d895768597e9a96","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fef93a720d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750329658096,"stop":1750329794563,"duration":136467}},{"uid":"8866ef8204c5ada2","reportUrl":"https://pagopa.github.io/rtp-platform-qa/394//#testresult/8866ef8204c5ada2","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff1ed2f3250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750317554072,"stop":1750317689390,"duration":135318}},{"uid":"6a86782bd4889d12","reportUrl":"https://pagopa.github.io/rtp-platform-qa/392//#testresult/6a86782bd4889d12","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f06a5323610>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750230495644,"stop":1750230630050,"duration":134406}},{"uid":"5efa80e6d2db29d2","reportUrl":"https://pagopa.github.io/rtp-platform-qa/390//#testresult/5efa80e6d2db29d2","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd5ea0f3390>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750170142004,"stop":1750170278196,"duration":136192}},{"uid":"d83e9d7e8739655b","reportUrl":"https://pagopa.github.io/rtp-platform-qa/389//#testresult/d83e9d7e8739655b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1c28c21e50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750144060530,"stop":1750144194619,"duration":134089}}]},"tags":["poste","send","happy_path"]},"source":"389be36f8544bbfe.json","parameterValues":[]}